# Generated by Django 5.0.3 on 2024-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
