# Generated by Django 5.0.3 on 2024-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_author_mobile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="authors_pictures"
            ),
        ),
    ]
